import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lexical Editor</title>
        <meta name="description" content="Generated by create next app." />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {"Let's try "}
          <a href="https://lexical.dev" target={"_blank"} rel={"noreferrer"}>
            Lexical!
          </a>
        </h1>
        <ul className={"mt-4 text-primary"}>
          <li>
            <Link href="/plain" passHref>
              <a className="lead">Plain Text Editor</a>
            </Link>
          </li>
          <li>
            <Link href="/rich" passHref>
              <a className="lead">Rich Text Editor</a>
            </Link>
          </li>
        </ul>
      </main>
    </div>
  );
};

export default Home;
